name: Build EXE for Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --add-data "troll.mp3;." bot_win.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: troll-bot-exe
        path: dist/bot_win.exe
